spring:
    datasource:
      url: jdbc:mysql://localhost:3306/spring_jwt
      username: root
      password: 123456789
      driver-classname: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true;
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect